# Gaza Vaccine Preventable Disease Immunity Modelling

This report summarises modelling to track the amount of immunity to various vaccine-preventabel diseases in Gaza over the course of the conflict.
The diseases currently modelled are:
- MMR:
- - Measles
- Pentavalent
- - Diphtheria
- - Pertussis
- - Hib Disease
- Rotavirus
- PCV
- - Pneumococcal Disease
- Polio
- - Polio (Wild-type)
- - Polio (Vaccine-derived)

## Model Details

INSERT MODEL STRUCTURE DIAGRAM

The model is an ODE model that tacks the waning of immunity to vaccinations based on defined coverage targets.
The model also simulates aquired immunity from pre-defined force of infection (FOI) values.

### Key Assumptions

- Death rates within each age group are constant across vaccination and disease status. The relative rate of death in each age group is assumed to be follow the distribution reported from 2019-2022.
- Crude birth rates are used so the birth are relative to the whole population, proportion of those born with maternal immunity is based on the proportions immune in the population between 15-45.
- Vaccine coverages are intepreted as a risk of being vaccinated within the relevant age group, and translated into instantaneous rates of vaccination. (add equation)
- To translate rates across age groups it is assumed that the rates are uniform within age groups, and to translate populations it is assumed the age distribution within each age group is flat.
- The model assumes that the population is closed and that there is no migration in or out of the population.
- The model assumes that the population is well-mixed and that there is no spatial structure to the population.

## Data

## Approach

* The model is not currently fitted to data and uses central estimates from the literature for all parameters. *

## Outputs

### Checking Demographics data

### Immunity projections