source("analysis/0_setup.R")
source("analysis/1_demographics.R")
source("analysis/2_diseases.R")
source("analysis/3_projections.R")
source("analysis/4_format.R")
library(rmarkdown)
rmarkdown::render("analysis/5_report.rmd", output_file = "../plots/report.html")
